dist: xenial
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      env: COVERAGE=true PUBLISH=true
    - python: 3.8

before_install:
  - bash ci/before_install.sh

# command to install dependencies
install:
  - bash ci/install.sh

# command to run tests
script:
  - bash ci/script.sh

# command to upload coverage
after_success:
  - bash ci/after_success.sh

deploy:
  provider: pypi
  on:
    condition: "$PUBLISH = true"
    tags: True
  distributions: "sdist bdist_wheel"
  user: rossmacarthur
  password:
    secure: NGd1nTpcXnV0/PmNdiWBWslJpOzZ0helir6p/wkrCnVwXCldq97xCc5H1ZthhsHEZQxtFrRaBCrhfTFNgVnf+4Plbo6aJTBj1KFfgQ2r6KkIqkQVvPRlBBwwlCEXJUlug3X9+7KQ6/PjX/ebJmJyPJP2wE9jNEZwfkUZLnVlB183j6jWacuoIW6JwL9HKqEYZi3tXZwu7RDxuJ7SWt6l1NAKbNIXwlJfwGfmrqljLSQHJtnvLRXRgsccQsqd3+rqJy1T1hahSUEfp/4deVcTdLhk2gI+mU5HE5jfa0iwGbeTIX6vLd3mVBDxaeVVBGZWVt/ZVNkHdzWZSaEP2gwlIUdFADq0ykJVv+TZ8fQn+/Ek2dmwlZpTXEbr4xJJICTQYlVacOqGZxLI0WgTQw4Kstc5eM5jLTdWTQKCkSJOWZEZU37SKJ0Gew5C9Qro4VUJZbhltvIe2MF848x4d5iN0rQMQN+XB7xnE4gcS7Uh8vwJajZKra7tsQmWVc+IIBs94DzZzlK/DQ1raZcLR3unVs3zkk0klsKTj30mA8ZnKOWti7WwNO2AIxJbULRRdfMUW3L1XIjFqCmKOrtJkXs9W1bEXUs/VItxIM0UYTj0F5ov0QioRm+KuDWIxgHYsg4d6FlCZZrPlQaz303j8IIDnCq9I5mKt2Sosgc9H7fpScQ=
